apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airbyte-connector
  name: airbyte-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte-connector
  template:
    metadata:
      labels:
        app: airbyte-connector
      name: airbyte-connector
    spec:
      containers:
        - name: airbyte-connector
          image: put/airbyte-connector
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9443
      serviceAccountName: airbyte-connector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: airbyte-connector
  name: airbyte-connector
spec:
  ports:
    - name: 9443-9443
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app: airbyte-connector
  type: ClusterIP
